### ISSUE TITLE
TLS Support?

### ISSUE THREAD

**Issue by bbuchalter** [martingordon/bronto-ruby#12]
Bronto just [recently announced](http://blogs.bronto.com/product/bronto-response-poodle-vulnerability) it is dropping support for SSL v3 and will require TLS on March 8th. Are there any steps we must take to make this library compatible?

**Comment by martingordon** [comment]
It looks like the SSL version is dependent on the underlying HTTP library used, so I just pushed a new version (0.3.1) that explicitly sets the SSL version to TLS.

Ref: fe3dc90dd2b71314cf163e79dd1bce0f9f538700
